# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

S3_KEY: AKIAI7LSUWJDGCUCBCCA
S3_SECRET: 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
development:
  S3_BUCKET_NAME: 'group3-railsdevelopment'   # Change this if you decide to create new bucket for development
#  S3_REGION: ''
production:
  S3_BUCKET_NAME: 'group3-railsproduction'
#  S3_REGION: ''

#S3_KEY: [KEY]
#S3_SECRET: [SECRET]
#development:
#  S3_BUCKET_NAME: '[dev_bucket]'
#  S3_REGION: ''
#production:
#  S3_BUCKET_NAME: '[production_bucket]'
#  S3_REGION: ''



gmail_username: 'masterchefgroup3@gmail.com'
gmail_password: 'cmpt276phoenix'
